### ISSUE TITLE
No TRX Deposit

### ISSUE THREAD

**Issue by MhizC** [Rovak/wallet-web#123] opened 2018-04-29 09:57 UTC
![screenshot_20180429-105534](https://user-images.githubusercontent.com/36557130/39405392-2f52845a-4b9c-11e8-9538-78d1f1da6532.png)
Hi dev, am having a bit of an issue here... After requesting for trx deposit my balance still reads 0. What might be the problem? System overlap?

**Comment by ritvick** [comment] 2018-04-30 16:53
Duplicate of #120

**Comment by segredor** [comment] 2018-05-02 12:36
I have the same issue.  I have waited days and still nothing.

**Comment by Rovak** [comment] 2018-05-02 13:44
@segredor could you try creating a new account and then request TRX again?

**Comment by segredor** [comment] 2018-05-03 00:43
I created a new account and it worked this time.

**Comment by MhizC** [comment] 2018-05-03 08:50
Thanks, I just tried it again and it worked!

**Closed as completed** 2018-05-08 20:14 UTC
